Build fixes
tidalcycles/Tidal pull request #1022
Opened 2023-06-24 00:26 UTC by exitmouse

I gather that `main` is unstable right now, and also it seems like most of the dev work is in `cycseq`. But...
I was trying to get Tidal to build anyway, so I figured I'd attempt to send a minimal PR that makes the build commands work. With these changes, on my local machine I can run
```
cabal v2-build --allow-newer=base,template-haskell --enable-tests --enable-benchmarks all
```
and then both `cabal v2-test` and `cabal v2-bench` run successfully. Hopefully that also means the CI will work.

I'm not totally sure that the Arc benchmarks I deleted should be deleted, but I couldn't find 2.0.0 equivalents for those functions. Let me know if I should replace them.

2023-06-24 09:45 UTC, yaxu requested changes
Thanks a lot for this, it would be great to get this building again. I've identified the missing functions if you fancy fixing those.

2023-06-24 09:45 UTC, yaxu commented on bench/Speed/Tidal/PatternB.hs
> -  [ bgroup "withQueryTime" [
This still exists, [in Sound.Tidal.Signal.Base](https://github.com/tidalcycles/Tidal/blob/78695cd30137fabaad0164ac490ba8c0c26d6bc4/src/Sound/Tidal/Signal/Base.hs#L403-L404)

2023-06-24 09:45 UTC, yaxu commented on bench/Speed/Tidal/PatternB.hs
> -withResultArcB :: [Benchmark]
This is now [withEventArc](https://github.com/tidalcycles/Tidal/blob/78695cd30137fabaad0164ac490ba8c0c26d6bc4/src/Sound/Tidal/Signal/Base.hs#L373-L377)

2023-06-24 09:45 UTC, yaxu commented on bench/Speed/Tidal/PatternB.hs
> -withQueryArcB :: [Benchmark]
This still exists [in Sound.Tidal.Signal.Base](https://github.com/tidalcycles/Tidal/blob/78695cd30137fabaad0164ac490ba8c0c26d6bc4/src/Sound/Tidal/Signal/Base.hs#L395-L396)

2023-06-24 09:45 UTC, yaxu commented on bench/Speed/Tidal/PatternB.hs
> -subArcB :: [Benchmark]
This is now [maybeSect in Sound.Tidal.Arc](https://github.com/tidalcycles/Tidal/blob/78695cd30137fabaad0164ac490ba8c0c26d6bc4/src/Sound/Tidal/Arc.hs#L36-L42)

2023-06-24 09:56 UTC, exitmouse commented
Thanks! I'm also going to try to understand these linking failures on the ci.

2023-06-24 16:03 UTC, exitmouse commented
Ok -- the ci check is green! The linker issue was because `dontcrash` tests `tidal-listener`, but `tidal-listener.cabal` recently added `-dynamic` in the build options, which stops ghc from building static object files. With `-dynamic-too` it should build both static and dynamic ones.
Nix and the windows build listener are still failing, but the errors are very early and don't seem to have anything to do with Tidal. Possibly bugs in the workflow files?

2023-06-24 16:14 UTC, exitmouse commented
The nix failures seem to be from https://github.com/cachix/install-nix-action/issues/183, and the windows build ones from https://github.com/haskell/actions/issues/264. Both seem like they just need version bumps... I'll see if I can try that.

2023-06-24 20:04 UTC, exitmouse commented
Well, now the nix build is failing because `hosc` has the wrong version in nixpkgs, and the windows build is failing because
>  when making flags consistent: warning:
>   -dynamic-too is not supported on Windows

2023-06-26 19:40 UTC, exitmouse commented
@mitchmindtree, I'm not sure if you're still maintaining this nix flake, but it appears (to my uneducated eye) that we need a version of `hosc` that's not available in nixpkgs, and I've got no idea how to get it. The failing nix builds are the last unsuccessful checks!

2023-06-28 07:43 UTC, yaxu commented
Thanks @exitmouse 

Yes looks like tidal is still on 1.9.2 in nixpkgs with the older hosc dependency. It seems it just grabs packages from stackage which does have the latest versions. Not sure how to get these versions bumped..

2023-06-28 07:45 UTC, yaxu commented
@polymorphicengine do the changes to the windows build here look good to you?

2023-06-28 07:51 UTC, polymorphicengine commented
yeah, compiling with `-dynamic-too` is right, not sure if we should disable the listener workflows at the moment though since they are all broken (they run through, but produce a binary that doesn't work properly)

2023-06-28 08:21 UTC, mitchmindtree commented
> Yes looks like tidal is still on 1.9.2 in nixpkgs with the older hosc dependency. It seems it just grabs packages from stackage which does have the latest versions. Not sure how to get these versions bumped..

Just to clarify, the version of tidal used in the Nix flake is the copy local to this repo.

It looks like the reason the build is failing is that the latest [pinned `hosc` version in nixpkgs is 0.19.1](https://github.com/NixOS/nixpkgs/blob/d0743034d0c163484791353ebd7fbe5e5cf03a1e/pkgs/development/haskell-modules/configuration-hackage2nix/stackage.yaml#L1127), whereas Tidal 2.0 now requires `hosc >=0.20 && <0.21`.

It looks like we can update `nixpkgs` by running the `update-stackage` script while `cd`'d into the root of the `nixpkgs` repo like so:

```
./maintainers/scripts/haskell/update-stackage.sh
```

but this updates the whole set of packages to their latest versions, so might take some time to review.

There's almost certainly a way to override `hosc` with the latest version locally in our `flake.nix` without waiting for all of nixpkgs to update - there's likely some answers in here https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/haskell.section.md, i'll do some digging soon.

2023-06-28 09:01 UTC, mitchmindtree commented
I've opened a PR against this branch that resolves the `hosc` `0.20` version issue here https://github.com/exitmouse/Tidal/pull/1.

2023-06-28 09:30 UTC, mitchmindtree commented
Out of curiosity, should `tidal-parse` and `tidal-listener` be building with the local `main` branch version of Tidal? Or is the plan to update those later on?

E.g. it looks like [`tidal-parse` still expects Tidal 1.10](https://github.com/tidalcycles/Tidal/blob/78695cd30137fabaad0164ac490ba8c0c26d6bc4/tidal-parse/tidal-parse.cabal#L33), and after fixing this `hosc` issue which allows the tidal lib to build it looks like the `tidal-listener` nix build continues to fail with a GHC panic:

```console
tidal-listener> [1 of 5] Compiling Sound.Tidal.Listener.Config ( src/Sound/Tidal/Listener/Config.hs, dist/build/Sound/Tidal/Listener/Config.p_o, dist/build/Sound/Tidal/Listener/Config.dyn_o )
tidal-listener> <no location info>: error:
tidal-listener>     ghc: panic! (the 'impossible' happened)
tidal-listener>   (GHC version 9.2.8:
tidal-listener>         lookupGlobal
tidal-listener>   Failed to load interface for ‘GHC.Num.BigNat’
tidal-listener>   Perhaps you haven't installed the "p_dyn" libraries for package ‘ghc-bignum’?
tidal-listener>   Use -v (or `:set -v` in ghci) to see a list of the files searched for.
tidal-listener>   Call stack:
tidal-listener>       CallStack (from HasCallStack):
tidal-listener>         callStackDoc, called at compiler/GHC/Utils/Panic.hs:181:37 in ghc:GHC.Utils.Panic
tidal-listener>         pprPanic, called at compiler/GHC/Tc/Utils/Env.hs:153:32 in ghc:GHC.Tc.Utils.Env
tidal-listener> Please report this as a GHC bug:  https://www.haskell.org/ghc/reportabug
tidal-listener>
tidal-listener> [3 of 5] Compiling Sound.Tidal.Listener.Parse ( src/Sound/Tidal/Listener/Parse.hs, dist/build/Sound/Tidal/Listener/Parse.p_o, dist/build/Sound/Tidal/Listener/Parse.dyn_o )
tidal-listener> <no location info>: error:
tidal-listener>     ghc: panic! (the 'impossible' happened)
tidal-listener>   (GHC version 9.2.8:
tidal-listener>         lookupGlobal
tidal-listener>   Failed to load interface for ‘GHC.Num.BigNat’
tidal-listener>   Perhaps you haven't installed the "p_dyn" libraries for package ‘ghc-bignum’?
tidal-listener>   Use -v (or `:set -v` in ghci) to see a list of the files searched for.
tidal-listener>   Call stack:
tidal-listener>       CallStack (from HasCallStack):
tidal-listener>         callStackDoc, called at compiler/GHC/Utils/Panic.hs:181:37 in ghc:GHC.Utils.Panic
tidal-listener>         pprPanic, called at compiler/GHC/Tc/Utils/Env.hs:153:32 in ghc:GHC.Tc.Utils.Env
tidal-listener> Please report this as a GHC bug:  https://www.haskell.org/ghc/reportabug
```

2023-06-28 12:11 UTC, yaxu commented
@mitchmindtree yep it'll take a some time to update tidal-parse. @polymorphicengine is working on fixing up tidal-listener builds, there's been some long running issues with the `hint` dependency blocking that but that might be solved soon.

2023-07-05 16:26 UTC, exitmouse commented
Hi, just checking in. Would you like me to add a commit to this PR to remove tidal-listener from the builds, so that the checks all pass? Or do you want to leave it in until it's fixed?

2023-07-05 16:34 UTC, polymorphicengine commented
yes, you can remove them for now! thanks!

2023-07-05 22:46 UTC, exitmouse commented
Alright! Sorry about the scope creep on this PR, and thanks @mitchmindtree for the nix changes!

2023-07-06 10:53 UTC, yaxu commented
Thanks all, is this ready to merge @exitmouse ?

2023-07-06 10:55 UTC, exitmouse commented
All good on my end. 👍

2023-07-06 11:16 UTC, merged

2023-07-06 11:16 UTC, yaxu commented
Thanks again!